name: Build Android APK

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            # Memanggil mesin Gradle langsung dari server GitHub tanpa butuh file gradlew lokal
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            # Mengompilasi dalam mode Debug agar APK otomatis ditandatangani dan siap instal
            - name: Build APK
              run: gradle assembleDebug

            - name: Upload APK ke Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: TrackerLocation-App
                  path: app/build/outputs/apk/debug/*.apk
